apiVersion: v1
kind: Service
metadata:
  name: cyber-backend-service
  labels:
    app: cyber-backend
spec:
  type: ClusterIP
  selector:
    app: cyber-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
