apiVersion: apps/v1
kind: Deployment
metadata:
  name: cyber-solutions
  labels:
    app: cyber-solutions
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cyber-solutions
  template:
    metadata:
      labels:
        app: cyber-solutions
    spec:
      containers:
        - name: cyber-solutions
          image: hassaan8345/cyber-solutions:fa23-bcs-118
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: MONGODB_URI
              value: "mongodb+srv://cybersolution:<YOUR_PASSWORD>@cluster0.lmjy4h1.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
            - name: NODE_ENV
              value: "production"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
