apiVersion: v1
kind: Service
metadata:
  name: cyber-frontend-service
  labels:
    app: cyber-frontend
spec:
  type: LoadBalancer
  selector:
    app: cyber-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
