apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cyber-mongo
spec:
  serviceName: "cyber-mongo"
  replicas: 1
  selector:
    matchLabels:
      app: cyber-mongo
  template:
    metadata:
      labels:
        app: cyber-mongo
    spec:
      containers:
        - name: mongo
          image: mongo:6.0
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongo-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: cyber-mongo
  labels:
    app: cyber-mongo
spec:
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None
  selector:
    app: cyber-mongo

